import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";
dotenv.config();


const textoLargo = `
{"evento.hora": "", "evento.fecha": "", "victima.sexo": "", "victima.zona": "Urbana", "evento.natural": "Ninguno", "vehiculo.marca": "", "vehiculo.placa": "", "apoderado.correo": "", "evento.direccion": "", "evento.municipio": "", "victima.telefono": "", "evento.terrorista": "Ninguno", "reclamacion.valor": "", "victima.condicion": "", "victima.direccion": "", "victima.municipio": "", "apoderado.telefono": "", "beneficiario.banco": "", "conductor.telefono": "", "evento.descripcion": "", "apoderado.direccion": "", "apoderado.municipio": "", "beneficiario.correo": "santiagoalfonso738@gmail.com", "conductor.direccion": "", "conductor.municipio": "", "evento.departamento": "", "beneficiario.celular": "", "propietario.telefono": "", "reclamacion.concepto": "", "vehiculo.aseguradora": "", "victima.departamento": "", "victima.fecha_muerte": "", "beneficiario.telefono": "", "propietario.direccion": "", "propietario.municipio": "", "victima.primer_nombre": "", "apoderado.departamento": "", "beneficiario.direccion": "Cl 78 C sur # 18 G 46", "beneficiario.municipio": "", "conductor.departamento": "", "vehiculo.aseguramiento": "", "vehiculo.numero_poliza": "", "vehiculo.tipo_servicio": "", "victima.segundo_nombre": "", "victima.tipo_documento": "", "apoderado.primer_nombre": "", "conductor.primer_nombre": "", "evento.otro_descripcion": "", "vehiculo.vigencia_desde": "", "vehiculo.vigencia_hasta": "", "victima.primer_apellido": "", "apoderado.segundo_nombre": "", "apoderado.tipo_documento": "", "beneficiario.tipo_cuenta": "", "conductor.segundo_nombre": "", "conductor.tipo_documento": "", "propietario.departamento": "", "victima.fecha_nacimiento": "", "victima.numero_documento": "", "victima.segundo_apellido": "", "apoderado.primer_apellido": "", "beneficiario.departamento": "", "conductor.primer_apellido": "", "propietario.primer_nombre": "", "apoderado.numero_documento": "", "apoderado.segundo_apellido": "", "beneficiario.primer_nombre": "Marlem", "conductor.numero_documento": "", "conductor.segundo_apellido": "", "propietario.segundo_nombre": "", "propietario.tipo_documento": "", "beneficiario.segundo_nombre": "", "beneficiario.tipo_documento": "", "propietario.primer_apellido": "", "beneficiario.cuenta_bancaria": "", "beneficiario.primer_apellido": "Alfonso", "propietario.numero_documento": "", "propietario.segundo_apellido": "", "apoderado.tarjeta_profesional": "", "beneficiario.numero_documento": "", "beneficiario.segundo_apellido": "Fonseca", "vehiculo.intervencion_autoridad": ""}
 {"evento.hora": "", "evento.fecha": "", "victima.sexo": "", "victima.zona": "Urbana", "evento.natural": "Ninguno", "vehiculo.marca": "", "vehiculo.placa": "", "apoderado.correo": "", "evento.direccion": "", "evento.municipio": "", "victima.telefono": "", "evento.terrorista": "Ninguno", "reclamacion.valor": "", "victima.condicion": "", "victima.direccion": "", "victima.municipio": "", "apoderado.telefono": "", "beneficiario.banco": "", "conductor.telefono": "", "evento.descripcion": "", "apoderado.direccion": "", "apoderado.municipio": "", "beneficiario.correo": "santiagoalfonso738@gmail.com", "conductor.direccion": "", "conductor.municipio": "", "evento.departamento": "", "beneficiario.celular": "", "propietario.telefono": "", "reclamacion.concepto": "", "vehiculo.aseguradora": "", "victima.departamento": "", "victima.fecha_muerte": "", "beneficiario.telefono": "", "propietario.direccion": "", "propietario.municipio": "", "victima.primer_nombre": "", "apoderado.departamento": "", "beneficiario.direccion": "Cl 78 C sur # 18 G 46", "beneficiario.municipio": "", "conductor.departamento": "", "vehiculo.aseguramiento": "", "vehiculo.numero_poliza": "", "vehiculo.tipo_servicio": "", "victima.segundo_nombre": "", "victima.tipo_documento": "", "apoderado.primer_nombre": "", "conductor.primer_nombre": "", "evento.otro_descripcion": "", "vehiculo.vigencia_desde": "", "vehiculo.vigencia_hasta": "", "victima.primer_apellido": "", "apoderado.segundo_nombre": "", "apoderado.tipo_documento": "", "beneficiario.tipo_cuenta": "", "conductor.segundo_nombre": "", "conductor.tipo_documento": "", "propietario.departamento": "", "victima.fecha_nacimiento": "", "victima.numero_documento": "", "victima.segundo_apellido": "", "apoderado.primer_apellido": "", "beneficiario.departamento": "", "conductor.primer_apellido": "", "propietario.primer_nombre": "", "apoderado.numero_documento": "", "apoderado.segundo_apellido": "", "beneficiario.primer_nombre": "Marlem", "conductor.numero_documento": "", "conductor.segundo_apellido": "", "propietario.segundo_nombre": "", "propietario.tipo_documento": "", "beneficiario.segundo_nombre": "", "beneficiario.tipo_documento": "", "propietario.primer_apellido": "", "beneficiario.cuenta_bancaria": "", "beneficiario.primer_apellido": "Alfonso", "propietario.numero_documento": "", "propietario.segundo_apellido": "", "apoderado.tarjeta_profesional": "", "beneficiario.numero_documento": "", "beneficiario.segundo_apellido": "Fonseca", "vehiculo.intervencion_autoridad": ""}
 {"evento.hora": "", "evento.fecha": "", "victima.sexo": "", "victima.zona": "Urbana", "evento.natural": "Ninguno", "vehiculo.marca": "", "vehiculo.placa": "", "apoderado.correo": "", "evento.direccion": "", "evento.municipio": "", "victima.telefono": "", "evento.terrorista": "Ninguno", "reclamacion.valor": "", "victima.condicion": "", "victima.direccion": "", "victima.municipio": "", "apoderado.telefono": "", "beneficiario.banco": "", "conductor.telefono": "", "evento.descripcion": "", "apoderado.direccion": "", "apoderado.municipio": "", "beneficiario.correo": "santiagoalfonso738@gmail.com", "conductor.direccion": "", "conductor.municipio": "", "evento.departamento": "", "beneficiario.celular": "", "propietario.telefono": "", "reclamacion.concepto": "", "vehiculo.aseguradora": "", "victima.departamento": "", "victima.fecha_muerte": "", "beneficiario.telefono": "", "propietario.direccion": "", "propietario.municipio": "", "victima.primer_nombre": "", "apoderado.departamento": "", "beneficiario.direccion": "Cl 78 C sur # 18 G 46", "beneficiario.municipio": "", "conductor.departamento": "", "vehiculo.aseguramiento": "", "vehiculo.numero_poliza": "", "vehiculo.tipo_servicio": "", "victima.segundo_nombre": "", "victima.tipo_documento": "", "apoderado.primer_nombre": "", "conductor.primer_nombre": "", "evento.otro_descripcion": "", "vehiculo.vigencia_desde": "", "vehiculo.vigencia_hasta": "", "victima.primer_apellido": "", "apoderado.segundo_nombre": "", "apoderado.tipo_documento": "", "beneficiario.tipo_cuenta": "", "conductor.segundo_nombre": "", "conductor.tipo_documento": "", "propietario.departamento": "", "victima.fecha_nacimiento": "", "victima.numero_documento": "", "victima.segundo_apellido": "", "apoderado.primer_apellido": "", "beneficiario.departamento": "", "conductor.primer_apellido": "", "propietario.primer_nombre": "", "apoderado.numero_documento": "", "apoderado.segundo_apellido": "", "beneficiario.primer_nombre": "Marlem", "conductor.numero_documento": "", "conductor.segundo_apellido": "", "propietario.segundo_nombre": "", "propietario.tipo_documento": "", "beneficiario.segundo_nombre": "", "beneficiario.tipo_documento": "", "propietario.primer_apellido": "", "beneficiario.cuenta_bancaria": "", "beneficiario.primer_apellido": "Alfonso", "propietario.numero_documento": "", "propietario.segundo_apellido": "", "apoderado.tarjeta_profesional": "", "beneficiario.numero_documento": "", "beneficiario.segundo_apellido": "Fonseca", "vehiculo.intervencion_autoridad": ""}
 `;



const ai = new GoogleGenAI({ apiKey: process.env.KEY });

async function main() {
  const response = await ai.models.generateContent({
    model: "gemini-2.0-flash",
    contents: "necesito que me digas el crreo del beneficiario"+textoLargo,
  });
  console.log(response.text);
}

main();